export const africanProverbs = [

{flag:"🇬🇭",nation:"Ghana",text:"Wisdom is like a baobab tree; no one individual can embrace it."},
{flag:"🇳🇬",nation:"Nigeria",text:"Until the lion learns to write, every story will glorify the hunter."},
{flag:"🇳🇬",nation:"Nigeria",text:"The child who washes his hands may dine with kings."},
{flag:"🌍",nation:"East Africa",text:"If you want to go fast, go alone. If you want to go far, go together."},
{flag:"🇪🇹",nation:"Ethiopia",text:"When spider webs unite, they can tie up a lion."},
{flag:"🇿🇦",nation:"South Africa",text:"Ubuntu: I am because we are."},
{flag:"🌍",nation:"Africa",text:"The child who is not embraced by the village will burn it down to feel its warmth."},
{flag:"🇬🇭",nation:"Ghana",text:"The ruin of a nation begins in the homes of its people."},
{flag:"🇬🇳",nation:"Guinea",text:"The one who asks questions never loses the way."},
{flag:"🇧🇫",nation:"Burkina Faso",text:"What an elder sees sitting down, a youth cannot see standing up."},
{flag:"🇳🇪",nation:"Niger",text:"A single bracelet does not jingle."},
{flag:"🌍",nation:"West Africa",text:"One finger cannot pick up a pebble."},
{flag:"🇰🇪",nation:"Kenya",text:"Sticks in a bundle are unbreakable."},
{flag:"🇱🇷",nation:"Liberia",text:"One broomstick breaks easily; a bundle does not."},
{flag:"🇨🇲",nation:"Cameroon",text:"A single hand cannot tie a bundle."},
{flag:"🇹🇬",nation:"Togo",text:"The hand washes the other."},
{flag:"🇬🇦",nation:"Gabon",text:"A canoe moves because many paddle."},
{flag:"🇲🇿",nation:"Mozambique",text:"The canoe reaches shore by many paddles."},
{flag:"🇸🇱",nation:"Sierra Leone",text:"The village raises the child."},
{flag:"🇨🇩",nation:"DR Congo",text:"A child belongs not to one parent but to the community."},
{flag:"🇧🇼",nation:"Botswana",text:"A calf belongs to the village."},
{flag:"🇬🇳",nation:"Guinea",text:"Knowledge is like a garden; if it is not cultivated, it cannot be harvested."},
{flag:"🌍",nation:"West Africa",text:"The fool speaks; the wise person listens."},
{flag:"🇬🇭",nation:"Ghana",text:"A wise person who knows proverbs can reconcile difficulties."},
{flag:"🇨🇲",nation:"Cameroon",text:"The ear that listens is wiser than the mouth that speaks."},
{flag:"🇸🇳",nation:"Senegal",text:"One who listens learns."},
{flag:"🇰🇪",nation:"Kenya",text:"A person who uses force is afraid of reasoning."},
{flag:"🇸🇴",nation:"Somalia",text:"Advice is a debt paid forward."},
{flag:"🇸🇴",nation:"Somalia",text:"A wise man is known by his actions."},
{flag:"🇪🇹",nation:"Ethiopia",text:"He who learns, teaches."},
{flag:"🇹🇬",nation:"Togo",text:"The one who learns is never poor."},
{flag:"🇱🇷",nation:"Liberia",text:"Do not look where you fell, but where you slipped."},
{flag:"🇲🇼",nation:"Malawi",text:"Little by little fills the basket."},
{flag:"🇲🇱",nation:"Mali",text:"The river is filled by many streams."},
{flag:"🇲🇺",nation:"Mauritius",text:"Many drops make an ocean."},
{flag:"🇬🇼",nation:"Guinea-Bissau",text:"Many hands make light work."},
{flag:"🇬🇲",nation:"Gambia",text:"The patient one eats ripe fruit."},
{flag:"🇸🇨",nation:"Seychelles",text:"Patience catches fish."},
{flag:"🇩🇿",nation:"Algeria",text:"Patience is the key to relief."},
{flag:"🇹🇳",nation:"Tunisia",text:"Patience is beautiful."},
{flag:"🇲🇷",nation:"Mauritania",text:"The desert rewards patience."},
{flag:"🇰🇲",nation:"Comoros",text:"The ocean teaches patience."},
{flag:"🇩🇯",nation:"Djibouti",text:"The patient camel reaches water."},
{flag:"🇲🇬",nation:"Madagascar",text:"The rice field grows by patience."},
{flag:"🇹🇩",nation:"Chad",text:"A journey is completed one step at a time."},
{flag:"🇬🇶",nation:"Equatorial Guinea",text:"The path is made by walking."},
{flag:"🇧🇮",nation:"Burundi",text:"A tree cannot stand without roots."},
{flag:"🇨🇮",nation:"Ivory Coast",text:"The river never forgets its source."},
{flag:"🇸🇸",nation:"South Sudan",text:"The river remembers its source."},
{flag:"🇳🇦",nation:"Namibia",text:"The track reveals the animal."},
{flag:"🇦🇴",nation:"Angola",text:"Rain beats the leopard's skin but does not wash away its spots."},
{flag:"🇿🇼",nation:"Zimbabwe",text:"The baboon laughs at the monkey's tail."},
{flag:"🇺🇬",nation:"Uganda",text:"Rain does not fall on one roof alone."},
{flag:"🇨🇻",nation:"Cape Verde",text:"The sea unites what the land divides."},
{flag:"🇸🇹",nation:"São Tomé & Príncipe",text:"The sea teaches humility."},
{flag:"🇸🇳",nation:"Senegal",text:"A guest is God's gift."},
{flag:"🇱🇾",nation:"Libya",text:"Trust in God, but tie your camel."},
{flag:"🇪🇷",nation:"Eritrea",text:"A good name is better than riches."},
{flag:"🇷🇼",nation:"Rwanda",text:"Unity is the foundation of strength."},
{flag:"🇹🇿",nation:"Tanzania",text:"Unity is strength, division is weakness."},
{flag:"🇪🇬",nation:"Egypt",text:"Consult the experienced before taking action."},
{flag:"🇲🇺",nation:"Mauritius",text:"The sugarcane bends but does not break."},
{flag:"🇿🇲",nation:"Zambia",text:"The patient bird eats the fattest worm."},
{flag:"🇸🇩",nation:"Sudan",text:"The one who plants dates does not expect to eat them."},
{flag:"🇸🇸",nation:"South Sudan",text:"Cattle unite the people."},
{flag:"🇿🇼",nation:"Zimbabwe",text:"The axe forgets; the tree remembers."},
{flag:"🇺🇬",nation:"Uganda",text:"A roaring lion kills no game."},
{flag:"🇹🇿",nation:"Tanzania",text:"The chameleon looks in all directions before moving."},
{flag:"🇳🇬",nation:"Nigeria",text:"A borrowed cloth does not keep one warm for long."},
{flag:"🇺🇬",nation:"Uganda",text:"He who climbs a good tree deserves a push."},
{flag:"🇲🇦",nation:"Morocco",text:"The eye never forgets what the heart has seen."},
{flag:"🇰🇪",nation:"Kenya",text:"The rainmaker does not fear the clouds."},
{flag:"🇬🇭",nation:"Ghana",text:"A drum sounds loud because it is empty inside."},
{flag:"🇪🇹",nation:"Ethiopia",text:"The hyena may change its den, but not its habits."}

];